Repository nteract/hydrogen, pull requests merged in 2019-07, with the labels that each got.

#1687 Make `Display` observer
  lib/components/result-view/display.js
Labels: bug :bug:, reviewable :heavy_check_mark:

#1688 Add Soft Wrapping To Config
  lib/components/result-view/history.js
  lib/components/result-view/list.js
  lib/components/result-view/result-view.js
  lib/config.js
  spec/components/result-view/history-spec.js
  spec/components/result-view/result-view-spec.js
  styles/hydrogen.less
  types/atom.js.flow
Labels: enhancement :star2:, refactor, reviewable :heavy_check_mark:

#1703 Improve Plotly Support
  lib/components/result-view/display.js
  lib/components/result-view/plotly.js
  package.json
  spec/components/result-view/plotly-spec.js
  styles/hydrogen.less
Labels: enhancement :star2:, refactor, reviewable :heavy_check_mark:

#1706 Refactor All Services APIs
  lib/components/status-bar.js
  lib/main.js
  lib/services/README.md
  lib/services/consumed/index.js
  lib/services/consumed/status-bar/index.js
  lib/services/consumed/status-bar/signal-list-view.js
  lib/services/consumed/status-bar/status-bar-component.js
  lib/services/consumed/status-bar/status-bar.js
  lib/services/index.js
  lib/services/provided/autocomplete.js
  lib/services/provided/index.js
  package.json
  spec/services/consumed/status-bar-spec.js
Labels: refactor, reviewable :heavy_check_mark:

#1712 Fix Kernel Command Bug Introduced in #1706
  lib/services/consumed/status-bar/status-bar.js
Labels: bug :bug:, reviewable :heavy_check_mark:

#1713 Fix #1564
  lib/zmq-kernel.js
Labels: bug :bug:, reviewable :heavy_check_mark:

#1718 Remove no longer needed libgconf2-4 addon
  .travis.yml
Labels: reviewable :heavy_check_mark:

#1717 Add missing quotations in Dockerfile example
  docs/Usage/RemoteKernelConnection.md
Labels: awaiting update, documentation :page_with_curl:

#1701 Watches Syntax Highlighting and Autocomplete
  lib/kernel.js
  lib/main.js
  lib/services/README.md
  lib/services/consumed/autocomplete.js
  lib/services/consumed/index.js
  lib/services/consumed/status-bar/index.js
  lib/services/consumed/status-bar/signal-list-view.js
  lib/services/consumed/status-bar/status-bar-component.js
  lib/services/consumed/status-bar/status-bar.js
  lib/services/index.js
  lib/services/provided/index.js
  lib/store/watch.js
  lib/store/watches.js
  package.json
  styles/hydrogen.less
  types/atom.js.flow
  types/autocomplete.js.flow
Labels: enhancement :star2:, reviewable :heavy_check_mark:
