Repository nteract/hydrogen, pull requests merged in 2019-05, with the labels that each got.

#1615 Activate the existing items in a dock in addition to showing the dock
  lib/utils.js
  types/atom.js.flow
Labels: enhancement

#1626 Use platform EOL for newlines
  spec/import-notebook-spec.js
Labels: bug, tests, windows

#1621 Update regexString
  lib/code-manager.js
  spec/code-manager-spec.js
Labels: enhancement

#1619 Add specs for kernel-monitor component
  lib/components/kernel-monitor.js
  spec/components/kernel-monitor-spec.js
Labels: tests

#1628 Implement Markdown Results
  lib/code-manager.js
  lib/main.js
  lib/store/index.js
  spec/code-manager-spec.js
  types/hydrogen.js.flow
Labels: enhancement
