Repository nteract/hydrogen, pull requests merged in 2019-08, with the labels that each got.

#1714 Refactor Result Code
  lib/kernel-manager.js
  lib/main.js
  lib/result.js
Labels: refactor, reviewable :heavy_check_mark:

#1727 Enhance autocomplete
  lib/config.js
  lib/services/provided/autocomplete.js
  package.json
  styles/hydrogen.less
  types/atom.js.flow
  types/autocomplete.js.flow
Labels: enhancement :star2:, reviewable :heavy_check_mark:

#1745 Update Cell Docs
  docs/Usage/Cells.md
  docs/Usage/GettingStarted.md
  docs/Usage/NotebookFiles.md
Labels: documentation :page_with_curl:

#1751 Create Doc Issue Template
  .github/ISSUE_TEMPLATE/documentation.md
Labels: discussion :speech_balloon:, reviewable :heavy_check_mark:
