Repository nteract/hydrogen, pull requests merged in 2019-06, with the labels that each got.

#1647 Fix Horizontal Scrolling of Result Views
  lib/components/result-view/result-view.js
Labels: bug, status: reviewable

#1637 Revert Accidental Change to Multi-Grammar Files
  lib/code-manager.js
Labels: bug :bug:, status: reviewable

#1652 Add Selecting Inside ResultViews
  lib/components/result-view/result-view.js
Labels: enhancement :star2:, reviewable :heavy_check_mark:

#1642 Drop Support For Re-evaluating Bubbles
  docs/Usage/GettingStarted.md
  lib/main.js
  package.json
Labels: discussion :speech_balloon:, help wanted, refactor

#1641 Update to @nteract/outputs
  lib/components/inspector.js
  lib/components/result-view/display.js
  lib/components/result-view/history.js
  lib/components/result-view/list.js
  lib/components/result-view/result-view.js
  lib/components/result-view/transforms.js
  lib/store/output.js
  package.json
Labels: refactor, reviewable :heavy_check_mark:

#1649 New Error For Import Notebook
  lib/import-notebook.js
Labels: bug :bug:, discussion :speech_balloon:, reviewable :heavy_check_mark:

#1655 Fix up outputs upgrade
  lib/components/result-view/display.js
  lib/components/result-view/history.js
  lib/components/result-view/list.js
  lib/components/result-view/result-view.js
  lib/components/result-view/transforms.js
  lib/store/output.js
  package.json
  spec/components/display-spec.js
Labels: refactor, reviewable :heavy_check_mark:

#1658 Fix to #807
  lib/autocomplete-provider.js
  lib/code-manager.js
  lib/utils.js
  lib/ws-kernel.js
  lib/zmq-kernel.js
Labels: bug :bug:, reviewable :heavy_check_mark:

#1659 Fix folding of cells
  lib/code-manager.js
Labels: bug :bug:, reviewable :heavy_check_mark:

#1661 Don't focus on kernel monitor after toggling
  lib/main.js
Labels: enhancement :star2:, reviewable :heavy_check_mark:

#1660 Fix #1603
  lib/components/kernel-monitor.js
  lib/store/index.js
  types/atom.js.flow
  types/electron.js.flow
  types/hydrogen.js.flow
  types/need-to-upstream-to-flow-lib.js.flow
Labels: bug :bug:, reviewable :heavy_check_mark:

#1664 Add supported image mediaTypes
  lib/components/result-view/display.js
Labels: bug :bug:

#1666 Fix the style of output list view
  styles/hydrogen.less
Labels: bug :bug:, reviewable :heavy_check_mark:

#1662 Add a callback for file delete event:
  lib/components/kernel-monitor.js
  lib/store/index.js
  lib/utils.js
Labels: discussion :speech_balloon:, enhancement :star2:, reviewable :heavy_check_mark:

#1682 Fix Editor Focus/Cursor Freezing
  lib/components/result-view/index.js
Labels: bug :bug:, reviewable :heavy_check_mark:

#1683 Upgrade to flow-bin 0.102.0
  lib/store/index.js
  package.json
  types/hydrogen.js.flow
Labels: chores, reviewable :heavy_check_mark:
